apiVersion: veecode.backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "platform_homolog_ec2"
  environment:
    cluster_type: ec2
    public_ip: 3.209.1.77
    domain: vkpr.platform.vee.codes
  annotations:
    github.com/project-slug: veecode-homolog/platform_homolog_ec2
    backstage.io/techdocs-ref: dir:.
    github.com/workflows: terraform-deploy.yml,start_instance.yml,stop_instance.yml,terraform-destroy.yml,deploy_dashboard
    cluster/instructions: |
      ssh -i ./key-pair.pem -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} "mkdir -p .kube && k3d kubeconfig get ${CLUSTER_NAME} > ~/.kube/config"
      scp -i ./key-pair.pem ${EC2_USER}@${EC2_HOST}:~/.kube/config ./config
      yq e 'del(.clusters[0].cluster.certificate-authority-data)' -i ~/.kube/config
      yq e '.clusters[0].cluster.insecure-skip-tls-verify=true' config -i
      yq e '.clusters[0].cluster.server = "https://${EC2_HOST}:38517"' config -i
spec:
  type: ec2
  lifecycle: experimental
  owner: "group:default/admin"
  environment: 'environment:default/platform_homolog_environment'
